// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Silverstar's Rock, Paper, Scissors",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Silverstar's Rock, Paper, Scissors",
            targets: ["AppModule"],
            bundleIdentifier: "one.hdcola.grace.rock-paper-scissors",
            teamIdentifier: "T4W3MN6QHA",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .arcadeGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
