let charater = Character()
let expert = Expert()
world.place(charater, facing: north, atColumn: 0, row: 0)
world.place(expert, facing: north, atColumn: 3, row: 0)
func clambUpAndDown() {
    charater.collectGem()
    charater.jump()
    charater.jump()
}
expert.toggleSwitch()
expert.turnLockUp()
clambUpAndDown()
clambUpAndDown()
charater.turnRight()
clambUpAndDown()
clambUpAndDown()
charater.turnLeft()
charater.collectGem()
charater.move(distance: 2)
charater.collectGem()
