let a = Expert()
world.place(a, facing: east, atColumn: 1, row: 7)
let b = Expert()
world.place(b, facing: south, atColumn: 5, row: 4)
let c = Expert()
world.place(c, facing: north, atColumn: 6, row: 4)
let bA = Block()
world.place(bA, atColumn: 2, row: 7)
let sA = Stair()
world.place(sA, facing: west, atColumn: 1, row: 6)
let pA = Portal(color: #colorLiteral(red: 0.9686274528503418, green: 0.7803921699523926, blue: 0.3450980484485626, alpha: 1.0))
world.place(pA, atStartColumn: 0, startRow: 6, atEndColumn: 2, endRow: 2)
let bB = Block()
world.place(bB, atColumn: 1, row: 2)
let sB = Stair()
world.place(sB, facing: west, atColumn: 2, row: 0)
let bC = Block()
world.place(bC, atColumn: 5, row: 3)

a.toggleSwitch()
a.moveForward()
a.turnRight()
a.moveForward()
a.toggleSwitch()
a.turnRight()
a.moveForward()
a.collectGem()
a.moveForward()
a.toggleSwitch()
a.moveForward()
a.turnLeft()
a.moveForward()
a.toggleSwitch()
for i in 1 ... 2 {
a.moveForward()
a.turnLeft()
}
a.moveForward()
a.collectGem()

b.toggleSwitch()
b.moveForward()
b.turnLeft()
b.moveForward()
b.toggleSwitch()

c.collectGem()
