let expert = Expert()
world.place(expert, atColumn: 2, row: 6)
func getGemTurnAndLock() {
    expert.turnRight()
    expert.moveForward()
    expert.collectGem()
    expert.turnLeft()
    expert.turnLeft()
    expert.moveForward()
    expert.turnLockUp()
    expert.turnRight()
}
getGemTurnAndLock()
expert.move(distance: 5)
getGemTurnAndLock()
expert.move(distance: 6)
expert.collectGem()
