func activatecomebCk() {
    moveForward()
    moveForward()
    toggleSwitch()
    turnLeft()
    turnLeft()
    moveForward()
    moveForward()
    moveForward()
    moveForward()
    toggleSwitch()
    turnLeft()
    turnLeft()
    moveForward()
    moveForward()
    turnLeft()
}

activatecomebCk()
moveForward()
moveForward()
toggleSwitch()
moveForward()
moveForward()
toggleSwitch()
turnLeft()
turnLeft()
moveForward()
moveForward()
moveForward()
moveForward()
moveForward()
moveForward()
toggleSwitch()
moveForward()
moveForward()
toggleSwitch()

