func moveThenToggle() {
    moveForward()
    moveForward()
    toggleSwitch()
    }
func turnAndMove() {
    turnLeft()
    turnLeft()
    moveForward()
    moveForward()
}
moveThenToggle()
turnAndMove()
moveThenToggle()
turnAndMove()
turnRight()
moveThenToggle()
moveThenToggle()
turnRight()
turnRight()
moveForward()
moveForward()
moveThenToggle()
moveThenToggle()
moveThenToggle()
