let greenPortal = Portal(color: #colorLiteral(red: 0.4028071761, green: 0.7315050364, blue: 0.2071235478, alpha: 1))
world.place(greenPortal, atStartColumn: 2, startRow: 5, atEndColumn: 6, endRow: 1)
collectGem()
moveForward()
turnLeft()
moveForward()
collectGem()
turnLeft()
turnLeft()
moveForward()
moveForward()
collectGem()
turnLeft()
turnLeft()
moveForward()
turnRight()
greenPortal.isActive = false
moveForward()
collectGem()
greenPortal.isActive = true
turnLeft()
turnLeft()
moveForward()
turnLeft()
turnLeft()
moveForward()
collectGem()
turnLeft()
turnLeft()
moveForward()
turnLeft()
moveForward()
collectGem()
turnLeft()
turnLeft()
moveForward()
moveForward()
collectGem()
turnLeft()
turnLeft()
moveForward()
turnRight()

moveForward()
collectGem()
