let block1 = Block()
let block2 = Block()
let block3 = Block()
let block4 = Block()
let block5 = Block()
world.place(block1, atColumn: 6, row: 2)
world.place(block2, atColumn: 4, row: 2)
world.place(block3, atColumn: 2, row: 2)
world.place(block4, atColumn: 2, row: 2)
world.place(block5, atColumn: 6, row: 2)
for i in 1 ... 3 {
    moveForward()
    moveForward()
    turnRight()
    toggleSwitch()
    move(distance: 4)
    collectGem()
    turnLeft()
    turnLeft()
    move(distance: 4)
    turnRight()
}
