let greenPortal = Portal(color: #colorLiteral(red: 0.4028071761, green: 0.7315050364, blue: 0.2071235478, alpha: 1))
world.place(greenPortal, atStartColumn: 5, startRow: 1, atEndColumn: 1, endRow: 5)
greenPortal.isActive = false
collectGem()
move(distance: 2)
collectGem()
turnLeft()
turnLeft()
moveForward()
turnLeft()
moveForward()
collectGem()
turnLeft()
turnLeft()
move(distance: 2)
collectGem()
turnLeft()
turnLeft()
greenPortal.isActive = true
moveForward()
moveForward()
turnLeft()
turnLeft()
greenPortal.isActive = false
collectGem()
move(distance: 2)
collectGem()
turnLeft()
turnLeft()
moveForward()
turnLeft()
moveForward()
collectGem()
turnLeft()
turnLeft()
move(distance: 2)
collectGem()
