let expert = Expert()
world.place(expert, facing: north, atColumn: 3, row: 0)
let character = Character()
world.place(character, facing: north, atColumn: 0, row: 0)
func turnAround() {
    character.turnLeft()
    character.turnLeft()
}
expert.toggleSwitch()
expert.turnLockUp()
character.collectGem()
character.jump()
character.jump()
character.collectGem()
character.jump()
character.jump()
character.collectGem()
world.place(character, facing: east, atColumn: 2, row: 4)
character.collectGem()
world.place(character, facing: north, atColumn: 4, row: 4)
character.collectGem()
character.move(distance: 2)
character.collectGem()
