let expert = Expert()
world.place(expert, atColumn: 2, row: 6)
expert.turnRight()
expert.moveForward()
expert.collectGem()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.turnLockUp()
expert.turnRight()
expert.move(distance: 5)
expert.turnLeft()
expert.turnLockUp()
expert.turnLeft()
expert.turnLeft()
expert.moveForward()
expert.collectGem()
expert.turnLeft()
expert.moveForward()
expert.turnLeft()
expert.moveForward()
expert.turnRight()
expert.move(distance: 5)
expert.collectGem()
