world.place(Stair(), facing: south, atColumn: 3, row: 3)
world.place(Stair(), facing: south, atColumn: 3, row: 1)
world.place(Stair(), facing: north, atColumn: 3, row: 7)
world.place(Stair(), facing: west, atColumn: 1, row: 5)
world.place(Stair(), facing: east, atColumn: 5, row: 5)
move(distance: 8)
toggleSwitch()
turnLeft()
moveForward()
toggleSwitch()
turnLeft()
turnLeft()
move(distance: 2)
toggleSwitch()
turnLeft()
turnLeft()
moveForward()
turnLeft()
move(distance: 3)
turnRight()
move(distance: 3)
toggleSwitch()
turnRight()
moveForward()
toggleSwitch()
turnLeft()
turnLeft()
move(distance: 2)
toggleSwitch()
turnLeft()
turnLeft()
moveForward()
turnRight()
move(distance: 6)
toggleSwitch()
turnLeft()
moveForward()
toggleSwitch()
turnLeft()
turnLeft()
move(distance: 2)
toggleSwitch()
