let expert = Expert()
world.place(expert, facing: west, atColumn: 3, row: 0)
expert.toggleSwitch()
world.place(expert, facing: west, atColumn: 0, row: 0)
expert.collectGem()
world.place(expert, facing: west, atColumn: 0, row: 2)
expert.collectGem()
world.place(expert, facing: west, atColumn: 0, row: 4)
expert.collectGem()
world.place(expert, facing: west, atColumn: 2, row: 4)
expert.collectGem()
world.place(expert, facing: west, atColumn: 4, row: 4)
expert.collectGem()
world.place(expert, facing: west, atColumn: 4, row: 6)
expert.collectGem()
