let felice =  Expert ()
world.place (felice, atColumn : 2 , row : 4 )
felice.toggleSwitch ()
world.place (felice, atColumn : 2 , row : 0 )
felice.collectGem ()
world.place (felice, atColumn : 4 , row : 4 )
felice.toggleSwitch ()
world.place (felice, atColumn : 4 , row : 0 )
felice.collectGem ()
world.place (felice, atColumn : 6 , row : 4 )
felice.toggleSwitch ()
world.place (felice, atColumn : 6 , row : 0 )
felice.collectGem ()
