let character = Character()
world.place(character, facing: .south, atColumn: 1, row: 7)
world.place(Block(), atColumn: 1, row: 1)
world.place(Block(), atColumn: 1, row: 6)
world.place(Block(), atColumn: 2, row: 2)
world.place(Block(), atColumn: 5, row: 4)
world.place(Block(), atColumn: 6, row: 3)
world.place(Portal(color: #colorLiteral(red: 0.0, green: 0.7790542245, blue: 0.9885957837, alpha: 1.0)), atStartColumn: 3, startRow: 6, atEndColumn: 1, endRow: 1)
func thing(){
    character.toggleSwitch()
    character.moveForward()
    character.collectGem()
    character.turnLeft()
    character.moveForward()
    character.toggleSwitch()
}
thing()
character.moveForward()
thing()
character.turnLeft()
character.turnLeft()
world.place(Portal(color: #colorLiteral(red: 1.0, green: 0.2527073622, blue: 0.07590860873, alpha: 1.0)), atStartColumn: 2, startRow: 1, atEndColumn: 6, endRow: 3)
character.moveForward()
character.turnLeft()
character.turnLeft()
thing()
