let expert = Expert()
let character = Character()
func move(){
    expert.moveForward()
    expert.moveForward()
}
expert.turnRight()
move()
expert.moveForward()
expert.turnLeft()
move()
expert.turnRight()
expert.turnLockUp()
expert.turnLeft()
move()
expert.turnLeft()
move()
move()
move()
expert.turnLeft()
move()
expert.turnRight()
expert.turnLockDown()
expert.turnLockDown()
character.moveForward()
character.moveForward()
character.collectGem()
character.moveForward()
character.moveForward()
character.toggleSwitch()
