let character = Character()
let expert = Expert()
func thing(){
    character.jump()
    character.jump()
    character.collectGem()
}
world.place(expert, facing: .north, atColumn: 3, row: 0)
expert.toggleSwitch()
expert.turnLockUp()
world.place(character, atColumn: 4, row: 6)
character.collectGem()
character.move(distance: 2)
character.collectGem()
character.turnRight()
thing()
thing()
character.turnLeft()
thing()
thing()
