let expert = Expert()
world.place(expert, facing: north, atColumn: 3, row: 0)
let character = Character()
world.place(character, facing: north, atColumn: 0, row: 0)
func collect() {
    character.collectGem()
    character.jump()
    character.jump()
    character.collectGem()
    character.jump()
    character.jump()
}
collect()
character.turnRight()
collect()
character.collectGem()
character.turnLeft()
expert.toggleSwitch()
expert.turnLockUp()
character.moveForward()
character.moveForward()
character.collectGem()
