let runrun = Expert()
world.place(runrun, atColumn: 2, row: 4)
runrun.toggleSwitch()
world.place(runrun, atColumn: 2, row: 0)
runrun.collectGem()
world.place(runrun, atColumn: 4, row: 4)
runrun.toggleSwitch()
world.place(runrun, atColumn: 4, row: 0)
runrun.collectGem()
world.place(runrun, atColumn: 6, row: 4)
runrun.toggleSwitch()
world.place(runrun, atColumn: 6, row: 0)
runrun.collectGem()
