//叫这个小破角色弄我，现在就搞搞他//
let character1 = Character()
let character2 = Character()
let character3 = Character()
let character4 = Character()
let character5 = Character()
let character6 = Character()
let character7 = Character()
let character8 = Character()
let character9 = Character()
let character10 = Character()
let character11 = Character()
let character12 = Character()


world.place(character1, facing: east, atColumn: 3, row: 2)
world.place(character2, facing: east, atColumn: 3, row: 2)
world.place(Gem(), atColumn: 3, row: 2)
world.place(character3, facing: east, atColumn: 4, row: 2)
world.place(character4, facing: east, atColumn: 4, row: 2)
world.place(Gem(), atColumn: 4, row: 2)
world.place(character5, facing: east, atColumn: 4, row: 3)
world.place(character6, facing: east, atColumn: 4, row: 3)
world.place(character7, facing: east, atColumn: 2, row: 3)
world.place(character8, facing: east, atColumn: 2, row: 3)
world.place(Gem(), atColumn: 2, row: 3)
world.place(Gem(), atColumn: 4, row: 3)
world.place(character9, facing: east, atColumn: 2, row: 2)
world.place(character10, facing: east, atColumn: 2, row: 2)
world.place(Gem(), atColumn: 2, row: 2)
var gem = 0
let s = 100
while gem != s {
    character1.turnLeft()
    character2.turnLeft()
    character3.turnLeft()
    character4.turnLeft()
    character5.turnLeft()
    character6.turnLeft()
    character7.turnLeft()
    character8.turnLeft()
    character9.turnLeft()
    character10.turnLeft()
    character1.collectGem()
    gem+=5
    character2.collectGem()
    character3.collectGem()
    character4.collectGem()
    character5.collectGem()
    character6.collectGem()
    character7.collectGem();  character8.collectGem()
    character9.collectGem()
    character10.collectGem()
    world.place(Gem(), atColumn: 4, row: 3)
    world.place(Gem(), atColumn: 4, row: 2)
    world.place(Gem(), atColumn: 3, row: 2)
    world.place(Gem(), atColumn: 2, row: 2)
    world.place(Gem(), atColumn: 2, row: 3)
}


