let character = Character()
world.place(character, atColumn: 6, row: 1)
character.collectGem()
world.place(character, atColumn: 1, row: 1)
character.collectGem()
world.place(character, atColumn: 1, row: 6)
character.collectGem()
