let character = Character()
let expert = Expert()
world.place(expert, atColumn: 3, row: 0)
expert.turnLeft()
expert.turnLeft()
expert.toggleSwitch()
expert.turnLockUp()
world.place(character, atColumn: 0, row: 0)
character.turnLeft()
character.turnLeft()
character.collectGem()
character.jump()
character.jump()
character.collectGem()
character.jump()
character.jump()
character.collectGem()
character.turnRight()
character.jump()
character.jump()
character.collectGem()
character.jump()
character.jump()
character.collectGem()
character.turnLeft()
character.moveForward()
character.moveForward()
character.collectGem()
