let greenPortal = Portal(color: #colorLiteral(red: 0.4028071761, green: 0.7315050364, blue: 0.2071235478, alpha: 1))
let bluePortal = Portal(color: #colorLiteral(red: 0.2275036573, green: 0.5323064327, blue: 0.9950136542, alpha: 1.0))

let character = Character()
world.place(greenPortal, atStartColumn: 1, startRow: 6, atEndColumn: 2, endRow: 1)
world.place(Block(), atColumn: 2, row: 7)
world.place(Block(), atColumn: 1, row: 2)
world.place(character, atColumn: 1, row: 6)
character.turnLeft()
character.turnLeft()
character.collectGem()
character.jump()
character.toggleSwitch()
character.turnRight()
character.jump()
character.turnRight()
character.jump()
character.toggleSwitch()
character.turnRight()
character.jump()
character.collectGem()
character.jump()
character.toggleSwitch()
character.turnRight()
character.jump()
character.turnRight()
character.jump()
character.toggleSwitch()
world.place(bluePortal, atStartColumn: 3, startRow: 2, atEndColumn: 5, endRow: 3)
character.jump()
character.jump()
character.toggleSwitch()
character.turnLeft()
character.jump()
character.collectGem()
character.turnLeft()
character.jump()
character.toggleSwitch()
