let expert = Expert()
world.place(expert, facing: .south, atColumn: 1, row: 8)
expert.collectGem()
expert.moveForward()
expert.collectGem()
expert.moveForward()
expert.collectGem()
expert.moveForward()
expert.collectGem()
expert.turnLockDown()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.collectGem()
expert.moveForward()
expert.collectGem()
expert.turnLockUp()
expert.turnRight()
expert.moveForward()
expert.collectGem()
expert.moveForward()
expert.moveForward()
expert.collectGem()
expert.moveForward()
expert.collectGem()
