world.place(Block(), atColumn: 3, row: 3)
moveForward()
moveForward()
turnLeft()
moveForward()
moveForward()
moveForward()
turnRight()
moveForward()
moveForward()
moveForward()
turnLeft()
moveForward()
moveForward()
moveForward()
toggleSwitch()
