let block1 = Block()
let block2 = Block()
let block3 = Block()
world.place(block1, atColumn: 2, row: 2)
world.place(block2, atColumn: 4, row: 2)
world.place(block3, atColumn: 6, row: 2)
for i in 1 ... 3 {
    move(distance: 2)
    toggleSwitch()
    turnRight()
    move(distance: 1)
    jump()
    jump()
    move(distance: 1)
    collectGem()
    turnLeft()
    turnLeft()
    move(distance: 1)
    jump()
    jump()
    moveForward()
    turnRight()
}
