let blackPortal = Portal(color: #colorLiteral(red: 0.0, green: 0.0, blue: 0.0, alpha: 1.0))
let whitePortal = Portal(color: #colorLiteral(red: 0.9999960065, green: 1.0, blue: 1.0, alpha: 1.0))
let character = Character()
world.place(blackPortal, atStartColumn: 1, startRow: 2, atEndColumn: 5, endRow: 3)
world.place(whitePortal, atStartColumn: 7, startRow: 3, atEndColumn: 2, endRow: 7)
world.place(character, facing: east, atColumn: 2, row: 2)
func yeah() {
    character.turnRight()
    character.toggleSwitch()
    character.jump()
    character.collectGem()
    character.turnRight()
    character.jump()
    character.toggleSwitch()
    character.turnRight()
}
yeah()
character.jump()
character.jump()
yeah()
character.turnRight()
character.turnRight()
character.jump()
character.turnRight()
character.jump()
yeah()
