world.place(Stair(), facing: south, atColumn: 3, row: 3)
world.place(Stair(), facing: west, atColumn: 1, row: 4)
world.place(Stair(), facing: west, atColumn: 1, row: 5)
world.place(Stair(), facing: west, atColumn: 1, row: 6)
world.place(Stair(), facing: east, atColumn: 5, row: 6)
world.place(Stair(), facing: east, atColumn: 5, row: 5)
world.place(Stair(), facing: east, atColumn: 5, row: 4)
world.place(Stair(), facing: south, atColumn: 3, row: 1)
world.place(Stair(), facing: north, atColumn: 2, row: 7)
world.place(Stair(), facing: north, atColumn: 3, row: 7)
world.place(Stair(), facing: north, atColumn: 4, row: 7)
move(distance: 4)
turnLeft()
move(distance: 3)
toggleSwitch()
turnRight()
move(distance: 1)
toggleSwitch()
moveForward()
toggleSwitch()
turnRight()
move(distance: 6)
toggleSwitch()
turnRight()
moveForward()
toggleSwitch()
moveForward()
toggleSwitch()
turnRight()
move(distance: 2)
turnRight()
move(distance: 4)
toggleSwitch()
turnLeft()
moveForward()
toggleSwitch()
moveForward()
toggleSwitch()
