let death = Expert()
world.place(death, atColumn: 1, row: 6)
death.collectGem()
let murderer = Character()
world.place(murderer, atColumn: 6, row: 1)
murderer.collectGem()
let assasin = Expert()
world.place(assasin, atColumn: 1, row: 1)
assasin.collectGem()
