// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Biking Tracker",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Biking Tracker",
            targets: ["AppModule"],
            bundleIdentifier: "one.hdcola.biketracker",
            teamIdentifier: "T4W3MN6QHA",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationWhenInUse(purposeString: "Tracks your location to show map and calculate the path you’re taking."),
                .locationAlwaysAndWhenInUse(purposeString: "Tracks your location to show map and calculate the path you’re taking.")
            ],
            appCategory: .healthcareFitness
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)