let death = Expert()
world.place(death, facing: .north, atColumn: 5, row: 1)
death.collectGem()
death.moveForward()
death.collectGem()
let assassin = Expert()
world.place(assassin, facing: .north, atColumn: 5, row: 4)
assassin.collectGem()
assassin.moveForward()
assassin.collectGem()
assassin.turnLeft()
assassin.moveForward()
assassin.collectGem()
let murderer = Expert()
world.place(murderer, facing: .north, atColumn:  1, row: 5)
for i in 1 ... 3 {
    murderer.collectGem()
    murderer.moveForward()
}
murderer.collectGem()
