let death = Character()
world.place(death, facing: .north, atColumn: 0, row: 0)
death.collectGem()
death.jump()
death.jump()
death.collectGem()
let deathB = Character()
world.place(deathB, facing: north, atColumn: 0, row: 4)
deathB.collectGem()
let deathC = Character()
world.place(deathC, facing: north, atColumn: 2, row: 4)
deathC.collectGem()
let deathD = Character()
world.place(deathD, facing: north, atColumn: 4, row: 4)
deathD.collectGem()
let deathE = Character()
world.place(deathE, facing: north, atColumn: 4, row: 6)
deathE.collectGem()
let deathF = Expert()
world.place(deathF, facing: north, atColumn: 3, row: 0)
deathF.toggleSwitch()
