func forwardThenToggle() {
    moveForward()
    moveForward()
    toggleSwitch()
    
}
forwardThenToggle()
turnLeft()
turnLeft()
moveForward()
moveForward()
forwardThenToggle()
turnLeft()
turnLeft()
moveForward()
moveForward()
turnLeft()
forwardThenToggle()
forwardThenToggle()
turnLeft()
turnLeft()
moveForward()
moveForward()
moveForward()
moveForward()
forwardThenToggle()
forwardThenToggle()
